{{- if include "nextcloud.host" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nextcloud.fullname" . }}
  labels:
    app: {{ template "nextcloud.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "nextcloud.fullname" . }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
      - name: {{ template "nextcloud.fullname" . }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: {{ .Values.allowEmptyPassword | quote }}
        {{- if .Values.mariadb.enabled }}
        - name: MYSQL_HOST
          value: {{ template "nextcloud.mariadb.fullname" . }}
        - name: MYSQL_PORT_NUMBER
          value: "3306"
        - name: MYSQL_DATABASE
          value: {{ .Values.mariadb.mariadbDatabase | quote }}
        - name: MYSQL_USER
          value: {{ .Values.mariadb.mariadbUser | quote }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "nextcloud.mariadb.fullname" . }}
              key: mariadb-password
        {{- else }}
        - name: MYSQL_HOST
          value: {{ .Values.externalDatabase.host | quote }}
        - name: MYSQL_PORT_NUMBER
          value: {{ .Values.externalDatabase.port | quote }}
        - name: DATABASE_NAME
          value: {{ .Values.externalDatabase.database | quote }}
        - name: DATABASE_USER
          value: {{ .Values.externalDatabase.user | quote }}
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ printf "%s-%s" .Release.Name "externaldb" }}
              key: db-password
        {{- end }}
        - name: NEXTCLOUD_ADMIN_USER
          value: {{ default "" .Values.nextcloud.username | quote }}
        - name: NEXTCLOUD_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "nextcloud.fullname" . }}
              key: nextcloud-password
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /status.php
            port: http
            httpHeaders:
            - name: Host
              value: {{ include "nextcloud.host" . | quote }}
          initialDelaySeconds: 120
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /status.php
            port: http
            httpHeaders:
            - name: Host
              value: {{ include "nextcloud.host" . | quote }}
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 5
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: apache-data
          mountPath: /var/www/html
        - name: nextcloud-data
          mountPath: /var/www/html/data
        {{- range .Values.persistence.extraExistingClaimMounts }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          readOnly: {{ .readOnly }}
        {{- end }}
      volumes:
      - name: apache-data
      {{- if .Values.persistence.apache.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.apache.existingClaim }}{{ .Values.persistence.apache.existingClaim }}{{- else }}{{ template "nextcloud.fullname" . }}-apache{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: nextcloud-data
      {{- if .Values.persistence.nextcloud.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.nextcloud.existingClaim }}{{ .Values.persistence.nextcloud.existingClaim }}{{- else }}{{ template "nextcloud.fullname" . }}-nextcloud{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- range .Values.persistence.extraExistingClaimMounts }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .existingClaim }}
      {{- end }}
{{- end -}}
