apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nextcloud.fullname" . }}
  labels:
    app: {{ template "nextcloud.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.nextcloudPassword }}
  nextcloud-password: {{ .Values.nextcloudPassword | b64enc | quote }}
  {{ else }}
  nextcloud-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
